Repository BenoitAnastay/authelia-home-assistant-addon, pull requests merged in 2024-07, with the labels that each got.

#8 Update renovate.json
  .github/renovate.json
Labels: ci

#6 Add config filter support to addon configuration
  authelia/config.yaml
  authelia/rootfs/etc/s6-overlay/s6-rc.d/authelia/run
Labels: enhancement

#12 ⬆️ Update Authelia to v4.38.9
  authelia/Dockerfile
Labels: dependencies

#13 🐛 Add condition to apply filters
  authelia/rootfs/etc/s6-overlay/s6-rc.d/authelia/run
Labels: bug
